export const APP_CONSTANTS = {
  SAVE: 'Save',
  ADD_TASK: 'AddTask',
  VIEW_TASK: 'View Task',
  DELETE: 'Delete',
  UPDATE: 'Update',
  ROUTE_TO_ADD_TODO: 'addTodo',
  ROUTE_TO_VIEW_TODO: 'header/viewTodo',
  ROUTE_TO_HEADER_VIEW_TODO: 'viewTodo',
  HEADER_LABEL: 'Click Here To Add Todo',
  ROUTE_TO_UPDATE_TODO: 'header/updateTodo',
  SEARCH: 'Search',
  TOAST_TASK_ADD_SUCCESS_MESSAGE: 'Task Added Successfully!',
  TOAST_TASK_ADD_FAILED_MESSAGE: 'Failed Adding Todo Task!',
  TOAST_TASK_DELETE_SUCCESS_MESSAGE: 'Todo Deleted Succussfully!',
  TOAST_TASK_DELETE_FAILED_MESSAGE: 'Failed Deleting Task',
  TOAST_TASK_UPDATE_SUCCESS_MESSAGE: 'Update Successful!',
  TOAST_TASK_UPDATE_FAILED_MESSAGE: 'Failed updating...!',
  TOAST_TASK_ADD_DESCRIPTION_MESSAGE: 'Please Enter your Task Description',
};
